apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    version: {{ .Values.deployment.version }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        version: {{ .Values.deployment.version }}
      annotations:
        sidecar.istio.io/inject: "{{ .Values.deployment.enable_istio | default true }}"
    spec:
      containers:
        - name: app
          image: {{.Values.image }}
          imagePullPolicy: {{.Values.deployment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.nodePort }}
      {{- if .Values.deployment.nodeSelector.enabled }}
      nodeSelector:
        nodeGroupName	: {{ .Values.deployment.nodeSelector.nodeGroupName }}
      {{- end }}
      {{- if .Values.deployment.tolerations.enabled }}
      tolerations:
      - key	: {{ .Values.deployment.tolerations.key }}
        operator: {{ .Values.deployment.tolerations.operator }}
        value: {{ .Values.deployment.tolerations.value }}
        effect: {{ .Values.deployment.tolerations.effect }}
      {{- end }}
