apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    service: {{ .Values.serviceName }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.virtualService.host }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.deployment.nodePort }}
      name: http
      targetPort: {{ .Values.deployment.nodePort }}

