apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  gateways:
    - {{ .Values.namespace.name }}-gateway
  hosts:
    - {{ .Values.virtualService.host }}
  http:
  - route:
    - destination:
        host: {{.Values.serviceName }}
        subset: {{ .Values.deployment.version }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.serviceName }}
spec:
  host: {{ .Values.serviceName }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: {{ .Values.deployment.version }}
    labels:
      version: {{ .Values.deployment.version }}